# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-slim

WORKDIR /app

COPY pyproject.toml setup.py README.md LICENSE /app/
COPY alembic.ini /app/
COPY scripts /app/scripts
COPY src /app/src

# Patch out startup sleep to avoid delay
RUN sed -i 's/time\\.sleep(10)/pass/' /app/src/paelladoc/ports/input/mcp_server_adapter.py

# Install dependencies and package
RUN pip install --no-cache-dir .

# Expose MCP HTTP port
EXPOSE 8000

# Default to web transport (HTTP/SSE)
CMD ["python", "-m", "paelladoc.ports.input.mcp_server_adapter"]
