"""add_user_table

Revision ID: 473a64e48560
Revises: 2f250289cd7a
Create Date: 2025-04-24 13:58:37.207259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Remove unused import after adjustment
# from sqlalchemy.dialects import sqlite
import sqlmodel # Add this import for sqltypes

# revision identifiers, used by Alembic.
revision: str = '473a64e48560'
down_revision: Union[str, None] = '2f250289cd7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted ###
    op.create_table('userdb',
    sa.Column('id', sa.Integer(), nullable=False),
    # Correct the type: use sqlmodel.sql.sqltypes.AutoString() directly if needed, or sa.String
    sa.Column('user_identifier', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userdb_user_identifier'), 'userdb', ['user_identifier'], unique=True)
    # --- REMOVED incorrect autogenerated commands below --- #
    # op.drop_table('bucket_order')
    # op.drop_table('mece_dimensions')
    # op.drop_table('taxonomy_validations')
    # op.drop_table('behavior_configs')
    # op.drop_table('commands')
    # op.alter_column('artifactmetadb', 'id', ... )
    # op.alter_column('artifactmetadb', 'project_memory_id', ... )
    # op.alter_column('projectmemorydb', 'id', ... )
    # op.drop_index('ix_projectmemorydb_single_active', ... )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted ###
    # --- ADDED correct downgrade operations for removed commands --- #
    # op.create_index('ix_projectmemorydb_single_active', ... )
    # op.alter_column('projectmemorydb', 'id', ...)
    # op.alter_column('artifactmetadb', 'project_memory_id', ...)
    # op.alter_column('artifactmetadb', 'id', ...)
    # op.create_table('commands', ...)
    # op.create_table('behavior_configs', ...)
    # op.create_table('taxonomy_validations', ...)
    # op.create_table('mece_dimensions', ...)
    # op.create_table('bucket_order', ...)
    # --- Keep only downgrade for what was actually upgraded --- #
    op.drop_index(op.f('ix_userdb_user_identifier'), table_name='userdb')
    op.drop_table('userdb')
    # ### end Alembic commands ###
