"""sync models after fixing history

Revision ID: d8155dd520f3
Revises: 473a64e48560
Create Date: 2025-04-24 15:43:07.546523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd8155dd520f3'
down_revision: Union[str, None] = '473a64e48560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Comment out drop_table commands as these tables likely don't exist
    # op.drop_table('behavior_configs')
    # op.drop_table('mece_dimensions')
    # op.drop_table('taxonomy_validations')
    # op.drop_table('bucket_order')
    # op.drop_table('commands')
    
    # Apply other changes (type alterations, index changes)
    with op.batch_alter_table('artifactmetadb', schema=None) as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.NUMERIC(),
                   type_=sqlmodel.sql.sqltypes.GUID(),
                   existing_nullable=False)
        batch_op.alter_column('project_memory_id',
                   existing_type=sa.NUMERIC(),
                   type_=sqlmodel.sql.sqltypes.GUID(),
                   existing_nullable=False)

    with op.batch_alter_table('projectmemorydb', schema=None) as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.NUMERIC(),
                   type_=sqlmodel.sql.sqltypes.GUID(),
                   existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projectmemorydb', schema=None) as batch_op:
        batch_op.alter_column('id',
                   existing_type=sqlmodel.sql.sqltypes.GUID(),
                   type_=sa.NUMERIC(),
                   existing_nullable=False)

    with op.batch_alter_table('artifactmetadb', schema=None) as batch_op:
        batch_op.alter_column('project_memory_id',
                   existing_type=sqlmodel.sql.sqltypes.GUID(),
                   type_=sa.NUMERIC(),
                   existing_nullable=False)
        batch_op.alter_column('id',
                   existing_type=sqlmodel.sql.sqltypes.GUID(),
                   type_=sa.NUMERIC(),
                   existing_nullable=False)
                   
    # Re-create tables if needed for downgrade, ensure types match old state
    # op.create_table('commands', ... )
    # op.create_table('bucket_order', ... )
    # op.create_table('taxonomy_validations', ... )
    # op.create_table('mece_dimensions', ... )
    # op.create_table('behavior_configs', ... )
    # ### end Alembic commands ###
