theme: jekyll-theme-primer
title: Paella Doc
description: AI-powered interactive documentation generator
baseurl: /paelladoc
url: https://jlcases.github.io
show_downloads: true
source: pages
github:
  repository_url: https://github.com/jlcases/paelladoc
  owner_url: https://github.com/jlcases

# Custom settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - docs 