# .github/workflows/ci.yml
name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
        env:
          UV_HOME: /home/runner/.uv
        shell: bash
        
      - name: Add uv to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH
        shell: bash

      - name: Create and Activate Virtual Environment
        run: |
          uv venv .venv
          echo ".venv/bin" >> $GITHUB_PATH
        shell: bash

      - name: Install Dependencies and Dev Dependencies
        run: |
          source .venv/bin/activate
          # Install project dependencies
          uv pip install -e .
          # Install test dependencies directly
          uv pip install pytest==8.3.2 pytest-asyncio==0.23.8 requests==2.32.3
          python -m pip list  # Debug: list installed packages
        shell: bash
        
      - name: Install mcp-sdk from Git
        run: |
          source .venv/bin/activate
          uv pip install git+https://github.com/modelcontextprotocol/python-sdk.git
        shell: bash

      - name: Run tests
        run: |
          source .venv/bin/activate
          python -m pytest -q
        shell: bash