# .github/workflows/ci.yml
name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
        env:
          UV_HOME: /home/runner/.uv
        shell: bash
        
      - name: Add uv to PATH
        # Using the default uv install path now which is often $HOME/.local/bin
        # Or it might be $UV_HOME/bin. Let's try the more standard approach.
        # The install script message usually tells the correct path.
        # Trying $HOME/.local/bin first.
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH
        shell: bash

      - name: Create and Activate Virtual Environment
        run: |
          uv venv .venv # Create venv using uv
          source .venv/bin/activate # Activate it for subsequent steps
        shell: bash

      - name: Install Dependencies (excluding mcp-sdk)
        # Now uv should find and use the activated .venv
        run: uv pip install -e '.[dev]' 
        shell: bash
        
      - name: Install mcp-sdk from Git
        run: uv pip install git+https://github.com/modelcontextprotocol/python-sdk.git
        shell: bash

      - name: Run tests
        run: pytest -q
        shell: bash # Ensure pytest runs in the activated venv